apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-data-ips
  name: postgres-data-ips
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
status: {}